apiVersion: apps/v1
kind: Deployment
metadata:
  name: knative-eventing-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: knative-eventing-operator
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        name: knative-eventing-operator
    spec:
      serviceAccountName: knative-eventing-operator
      containers:
        - name: knative-eventing-operator
          image: knative.dev/eventing-operator/cmd/manager
          imagePullPolicy: IfNotPresent
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: METRICS_DOMAIN
              value: knative.dev/operator-operator
